[agent]
numworkers=3
port=5600
transferpath=$(wt.temp)\transfer
;
[worker1]
distributed=false
autostart=true
host=SWIFTPLM-PC-01
autobusystop=
autoidlestop=
starttime=3600
startfromlocal=FALSE
autoerrorstop=false
hosttype=local
remotepath=
exe=C:\ptc\creo_view_adapters_120\proe_setup\proeworker.bat
localpath=ftp:
maxinstances=1
queueset=INWORK
shapetype=PROE
availabletime=
port=601
;
[worker2]
distributed=false
autostart=true
host=SWIFTPLM-PC-01
autobusystop=
autoidlestop=
starttime=3600
startfromlocal=FALSE
autoerrorstop=false
hosttype=local
remotepath=
exe=C:\ptc\creo_view_adapters_120\doc_setup\docworker.bat
localpath=ftp:
maxinstances=1
shapetype=OFFICE
availabletime=
port=603
;
[worker3]
distributed=false
autostart=true
host=SWIFTPLM-PC-01
autobusystop=
autoidlestop=
starttime=3600
startfromlocal=FALSE
autoerrorstop=false
remotepath=
hosttype=local
localpath=ftp:
exe=C:\ptc\creo_view_adapters_120\proe_setup1\proeworker.bat
maxinstances=1
queueset=RELEASED
shapetype=PROE
availabletime=
port=602
;
